@Henry.Api_HostAddress = https://localhost:5000

POST {{Henry.Api_HostAddress}}/providers
Content-Type: application/json

{
  "name": "Henry"
}

###

POST {{Henry.Api_HostAddress}}/clients
Content-Type: application/json

{
  "name": "Lando Calrisian",
  "email": "TheResponsibleLando@cloudcity.bespin"
}

###
