@Henry.Api_HostAddress = https://localhost:7281

POST {{Henry.Api_HostAddress}}/api/v0/providers
Content-Type: application/json

{
  "name": "Henry"
}

###

POST {{Henry.Api_HostAddress}}/api/v0/clients
Content-Type: application/json

{
  "name": "Lando Calrisian",
  "email": "TheResponsibleLando@cloudcity.bespin"
}

###
